export default {
  colorWhite: '#FFFFFF',
  colorRed: '#F05B48',
  colorGreen: '#10BC90',
  colorYellow: '#D8B080',
  colorBlue: '#4c90c7',
  // 文本主色
  textColor: '#333333',
  // 文本副色
  textColor2: '#999999',
  textColor3: '#515151',
  textColor4: '#3D3D3D',
  // 背景主色
  bgColor: '#F1F1F3',
  // 背景副色
  bgColor2: '#FFFFFF',
  bgColor3: '#FFFFFF',
  bgColor4: '#FFFFFF',
  // 渐变背景色
  gradualBgColor1: '#FFFFFF',
  gradualBgColor2: '#FFFFFF',
  // 高亮颜色
  underlayColor: '#D8B080',
  // 线条主色
  lineColor: '#E0E0E0',
  // 输入框底线的颜色
  lineInputColor: '#CCCCCC',

  placeholderColor: '#515151',
  // 按钮文本
  buttonTextColor: '#333333',
  // iNumber组件样式
  iNumberBorderColor: '#515151',
  iNumberDisableBorderColor: '#999999',
  iNumberDisableBgColor: '#ffffff',
  iNumberOperatorBorderColor: '#515151',
  // 边框颜色
  borderColor: '#999999',
  // 根页面tab条边框颜色
  tabBarBorderColor: '#cccccc',
  userIconBgColor: '#EEEEEE',
  // 链接颜色
  linkColor: '#4c90c7',
  // 占位图颜色
  imgHolderColor: '#BBBBBD',
  // 输入框边框颜色
  editTextBorderColor: '#858DA0',
};
